# Generated by Django 3.2 on 2023-07-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cupos',
            field=models.IntegerField(default=1),
        ),
    ]
