# Generated by Django 3.2 on 2023-07-16 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_empresa_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('0', 'Pendiente'), ('1', 'Aceptado')], default=0, max_length=1)),
                ('nro_Solicitud', models.CharField(max_length=50)),
                ('cupos', models.IntegerField(default=1)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.alumno')),
            ],
        ),
    ]
