# Generated by Django 3.2 on 2023-07-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_empresar'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='whatsApp',
            field=models.CharField(max_length=20),
        ),
    ]
